Laboratoria/curriculum

04-social-network/02-jquery/02-selectors/README.md

Corrección en la línea 42, para acceder a varias clases se escriben todas dentro de la mismas comillas y no por separado
`$('.pink .blue .red');` en vez de `$('.pink', '.blue', '.red');`

corrección 02-selectors selector por class

---

14-chatbot/01-challenge/00-opening/README.md
14-chatbot/01-challenge/02-env/README.md
14-chatbot/02-getting-started/01-design-principles/README.md
14-chatbot/02-getting-started/02-ms-bot-framework/README.md

Cambios se enviaron via slack #464

content(14-chatbot): añade cambios propuestos por @ccardensa

---

11-react/02-babel-and-webpack/07-quiz/README.md

@lupomontero envío PR del quiz correspondiente a la unidad 02-babel-and-webpack
Quedo atenta a cualquier comentario 🚀

React quiz unidad 02-babel-and-webpack

---

projects/01-cipher/package.json

Para el proyecto Cipher, si los tests fallaran al final del output vemos lo siguiente:
Este PR agrega el flag `--silent`[[1]] al comando npm run que usamos para correr los tests, de esa manera el output será:
Esto puede ayudar a las estudiantes en enfocarse en los demás contenidos del log que sí indican que tests siguen fallando. Y esconde un texto que las puede confundir.
Mocha tiene ese comportamiento por defecto y es usado cuando se trabaja con servidores y CIs, no siendo el caso para este proyecto.
Conversación sobre un silent flag para mocha: https://github.com/mochajs/mocha/issues/138
[1]: https://docs.npmjs.com/misc/config#loglevel

project(cipher): Prevenir a Mocha de mostrar errores de stdout cuando los tests fallan

---

projects/01-cipher/.babelrc
projects/01-cipher/.eslintrc
projects/01-cipher/.gitignore
projects/01-cipher/README.md
projects/01-cipher/README.pt-BR.md
projects/01-cipher/package.json
projects/01-cipher/src/cipher.js
projects/01-cipher/src/index.html
projects/01-cipher/src/index.js
projects/01-cipher/test/.eslintrc
projects/01-cipher/test/cipher.spec.js

Related:
* https://github.com/Laboratoria/bootcamp/pull/870
* https://github.com/Laboratoria/bootcamp/issues/840
* https://github.com/RuthSalvador/curricula-js/pull/2

project(cipher): Introduces ES Modules

---

projects/02-data-lovers/README.md
projects/02-data-lovers/README.pt-BR.md

closes #838 
Although the files that were shared somehow could help the students to have an idea of what to expect of this project. Using `.sketch` or `.psd` files could restrict their ability to access  those resources (not everyone has the propietary software to open them). And while there was one that had a `.pdf` extension, we could create a bias towards using that data-set instead of the others without a visual identity.
Let's take a step back and rethink the benefits of providing these files and the format in which we can share them.

Remove visual identity paragraph

---

README.md
projects/01-card-validation/README.md
projects/01-cipher/README.md
projects/01-cipher/README.pt-BR.md
projects/02-data-lovers/README.md
projects/02-data-lovers/README.pt-BR.md
projects/03-small-businesses/README.md
projects/03-social-network/README.md
projects/04-burger-queen/README.md
projects/04-md-links/README.md
projects/04-md-links/README.pt-BR.md
projects/04-redesign-and-data/README.md
projects/04-social-network-frameworks/README.md
projects/05-bq-node/README.md
projects/05-tic-tac-toe-rn/README.md
projects/05-ux-consultancy/README.md
projects/06-service-design/README.md
projects/06-visual-design/README.md

This change replaces the assessment (evaluación) section in individual
project readme's. These sections used to list a bunch of skills from the
already deprecated rubric (v3.x). These are being replaced by the
learning objetives (objetivos de aprendizaje) found elsewhere on the
readmes.
Instead if having assessment info in each readme, this PR proposes that
this info be shared by ALL projects and thus live outside of the project
readmes. As such, the project assessment info is being added to the main
repo readme (independent from individual projects).
Also note that the language has been tweaked a bit to make it more
generic and also to avoid abusing the word "evaluación".
Closes #881

chore(projects): Replaces project specific assessment section with generic text

---

projects/02-data-lovers/README.md

This attempts to close https://github.com/Laboratoria/bootcamp/issues/948
We use what has worked for the json files.

Update research links to use project folder as root

---

projects/04-md-links/.eslintrc

* Cambia `env` de `browser` a `node` (esto estaba mal :scream:)
* Aumenta versión del parser de ES a 8.

Arregla conf de eslint en proyecto md-links

---

projects/02-emergency-room/README.md
projects/02-movie-challenge/README.md
projects/03-visitors/README.md
projects/04-news-alerts/README.md
projects/06-open-project/README.md

Ahora estos proyectos apuntan a un listado que puede cambiar en el tiempo,
esta estrategia me pareció más consciente al tiempo que escribir todos los
objetivos de aprendizaje por cada proyecto.

Agrega referencia a listado de objetivos de aprendizaje

---

projects/01-cipher/test/cipher.spec.js

`cipher.decode` function test was actually calling the `cipher.encode`. This PR fixes it.

Fix cipher decode test function

---

projects/00-trivia/README.md
projects/00-trivia/README.pt-BR.md
projects/01-card-validation/README.md
projects/01-cipher/README.md
projects/02-data-lovers/README.md
projects/02-data-lovers/README.pt-BR.md
projects/02-memory-match/README.md
projects/03-social-network/README.md
projects/03-social-network/README.pt-BR.md
projects/04-burger-queen-api-client/README.md
projects/04-burger-queen/README.md
projects/learning-objectives.md

Desde hace ya un tiempo se ha venido conversando la idea de quitar este objetivo de aprendizaje (_Construir tu aplicación respetando el diseño realizado_), ya que no consideramos que sea un objetivo de aprendizaje como tal, si no más bien un criterio de aceptación del proyecto en cuestión. Este cambio afecta a los proyectos `trivia`, `card-validation`, `cipher`, `data-lovers`, `memory-match`, `social-network`, `burger-queen`, `burger-queen-api-client`.

Removes obsolete learning objective 'Construir tu aplicación respetando el diseño realizado'

---

projects/04-burger-queen-api/GETTING-STARTED.md
projects/04-burger-queen-api/README.md
projects/04-burger-queen-api/docker-compose.yml
projects/04-burger-queen-api/sample.secrets.env

Este PR agrega un [archivo](https://github.com/lupomontero/bootcamp/blob/feat/burger-queen-api-1016/projects/04-burger-queen-api/GETTING-STARTED.md) con información sobre cómo arrancar con el entorno de desarrollo en el proyecto de `burger-queen-api`, que es normalmente su 1er proyecto de _backend_ y la 1era vez que se topan con bases de datos y docker.
Las instrucciones tratan de cubrir las 3 opciones de bases de datos (MySQL, Postgres y MongoDB), pensando no solo en estudiantes si no también como guía para el equipo de coaches, y sobretodo pensando en el piloto de la extensión de bootcamp, donde también estaremos usando este proyecto, y nos interesa que pueden elegir cualquiera de las 3 opciones.
Para facilitar el _setup_, me he tomado la libertad de eliminar el archivo de _secretos_ y …

project(burger-queen-api): Adds info to help choose a db and get started with docker

---

projects/00-trivia/README.md
projects/00-trivia/README.pt-BR.md
projects/01-card-validation/README.md
projects/01-card-validation/README.pt-BR.md
projects/01-cipher/README.md
projects/02-data-lovers/README.md
projects/02-data-lovers/README.pt-BR.md
projects/02-memory-match/README.md

Siguiendo con la conversación iniciada por @AdrianaHY en Slack (canal `#equipo-bootcamp-reg`), este PR propone quitar el requerimiento de "_no usar la pseudo-variable `this`_" en los proyectos. En principio esta conversación surgió con respecto al proyecto `trivia` usado durante el proceso de _preBootcamp_ (aka _pre admisión_), ya que parece que causa bastantes dudas innecesarias sobre `this` y toda la complejidad y sutilezas que conlleva en JavaScript.
Como contexto, es algo que hemos heredado de hace años, cuando todavía la mayoría de ejemplos que uno encontraba en internet hacían uso y abuso the `this`, que, antes de la funciones flechas y el ámbito de bloque, eran trampas en las que podíamos caer muy fácilmente.
Varias coaches se han mostrado a favor del cambio para evitar confusión …

Quita requerimiento de evitar pseudo-variable this

---

projects/01-card-validation/package.json
projects/01-cipher/package.json
projects/02-data-lovers/package.json
projects/02-emergency-room/package.json
projects/02-memory-match/package.json
projects/03-social-network/package.json

Soluciona #1116 y sube la versión de `serve` a la más nueva.

chore(projects): Agrega opción `-s` a ejecución de `serve` y sube la versión a 13.0.2

---

.github/workflows/main.yml

Change test matrix on `push` job to use node versions 16 and 18 (instead of 14 and 16).

fix(ci-cd)

---

projects/02-data-lovers/README.pt-BR.md

Fixing un error de traducción en la explicación de la data de League of Legends
Una estudiante me he apuntado y es correcto:
La data es sobre los champions (campeões) del juego y no sobre los jugadores (jogadores)

📄 docs: fix translation

---

learning-objectives/intl/es.yml
learning-objectives/intl/pt.yml

Addresses #1209 
Agregamos `title:` explicitamente a cada encabezado. 
Estes cambios arreglan user centricity y product design en particular.
Aqui es un primer avance, falta:
Probando usando `create-cohort-project` y viendo el resultado
en ES y PT:
https://gist.github.com/unjust/83cba0bc007c2251219bc60286e54fc2
(con `npm run create-cohort-project ./projects/01-cipher  ../../temp TEST-BR -- --locale=pt-BR`)

agrega titulos a OAs 

---

projects/04-burger-queen-api/README.md

Se propone quitar Heroku de las opciones de despliegue ya que en 3 semanas finaliza su capa gratuita, una buena alternativa es Glitch que tiene soporte para node y expressJS. Adicionalmente se sugiere ElephantSQL para quienes deseen desplegar una base de datos relacional de Postgresql, este servicio también cuenta con una capa gratuita

doc: removed heroku and added glitch & elephantSql

---

DEPLOYMENT.md

chore(docs): Update DEPLOYMENT.md file

---

projects/01-cipher/README.md
projects/01-cipher/README.pt-BR.md

Propongo los siguientes cambios:
- En la seccion Preámbulo mejorar la explicacion sobre qué es cifrar
- En la seccion "8. Pistas, tips y lecturas complementarias", subseccion "Prepara tu PC para trabajar":
1. Eliminar referencia a Atom porque ya esta deprecated
2. Eliminar referencia a Windows Subsystem for Linux. Propongo eliminarlo porque las estudiantes suelen confundirse con esto e intentan configurar el WSL junto con Cmder y Git bash. Considero que es mejor si les ahorramos esta confucion. Por otro lado, en mi experiencia personal, WSL suele ser exigente para la máquina y supongo que las estudiantes que no tengan un computador bueno tendrian problemas. Y finalmente me parece un poco exagerado configurar todo WSL para algo sencillo como el primer proyecto. Dejo abierta la discusion. …

some improvements for cipher project

---

firebase.json

En `v6.0.0` el track de `js` de renombra oficialmente a `web-dev` de acuerdo con `@laboratoria/core`, por ende cambian las URLs que contenían `js` como representación del track.

feat(hosting): Agrega redirects de track js a web-dev

---

src/components/TopBar/index.jsx

Ver https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/256
En el próximo release de `bootcamp.laboratoria.la` se va a incluir este cambio, y toca replicarlo acá :stuck_out_tongue_winking_eye:

feat(TopBar): Quita título de menu de idioma

---

learning-objectives/intl/es.yml
learning-objectives/intl/pt.yml

Los backticks en los archivos de internacionalización de objetivos de aprendizaje estaba haciendo que el parser, al generar los proyectos, arrojara el siguiente error:
```
YAMLException: bad indentation of a mapping entry (1225:10)
1222 |       url: https://www.typescriptlang.o ...
1223 | 
1224 | typescript/classes/this:
1225 |   title: `this`
-----------------^
1226 |   links:
1227 |     - title: Documentación oficial de T ...
at generateError (file:///home/user/Documents/laboratoria/bootcamp/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
at throwError (file:///home/user/Documents/laboratoria/bootcamp/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
at readBlockMapping (file:///home/user/Documents/laboratoria/bootcamp/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
at composeNode …
```

fix(YML): Removes backticks from typescript/classes/this title in es and pt translations

---

scripts/create-cohort-project.mjs

Cambia el regex para buscar numbers > 9.
Antes el script tira un error por `10. Objetivos de aprendizaje` en Text Analyzer.
Hay que escribir tests en curriculum-parser para avisar de eso.

fix: change regex for oa heading fixes #1506

---

projects/05-fleet-management-api/project.yml

Este cambio propone que a partir de ahora los objetivos de aprendizaje (ya sean generales o de variante) se puedan expresar o como strings (estilo _legacy_) o como objetos. Cuando se expresen como objetos será obligatorio que contengan la propiedad `id` con el string que hubiéramos usado en estilo _legacy_ y opcionalmente podría tener las siguientes propiedades:
- `optional`: Por defecto `false`. Solo necesaria cuando queramos que sea `true`.
- `exlude`: Solo se puede usar dentro de los objetivos de las variantes, cuando queramos excluir objetivos declarados a nivel de todo el proyecto. Por defecto `false`. Solo necesaria cuando queramos que sea `true`.
Con el formato propuesto originalmente estábamos declarando OAs como objetos donde la única llave era el identificador del OA y el valor …

feat(projects/fleet-management-api): Cambia sintaxis de OAs a objeto sin anidación

---

projects/05-fleet-management-api/README.md
projects/05-fleet-management-api/postman/collection-auth.json
projects/05-fleet-management-api/postman/collection.json
projects/05-fleet-management-api/postman/environment.json

Addresses #1809 (continues #1817)
Aggrega
- Tests en el directorio `/postman` una coleccion sin auth y otro con auth
- Una seccion de readme sobre testing y como descargar newman
[Aqui es ejemplo output](https://gist.github.com/unjust/70eb522d164cfd764693aff3887ca084) para ver clara el tipo de tests que hay

Fleet management tests

---

learning-objectives/data.yml
learning-objectives/intl/es.yml
learning-objectives/intl/pt.yml
projects/05-salesforce/project.yml

Update Salesforce project.yml and objectives

---

learning-objectives/intl/es.yml

Hotfix, no links in devops OAs are killing the project page.
https://bootcamp.laboratoria.la/es/projects/container-service-deployment?version=v9.4.0

fix: remove blank links from devops objectives es.yml
