Laboratoria/curriculum

- 11-react/README.md
Se completa la tabla de contenidos para las las 7 lecciones del curso.
Además se adjuntan links de libros, benchmarks, etc. Una vez curados los linkeremos bonito.
todavia queda pendiente #56
> Tabla de contenido para las lecciones y recursos "literarios"

- 09-paradigms/04-proto.md
- 09-paradigms/05-solucionario.md
- 09-paradigms/06-game-oop.md
- 09-paradigms/README.md
- 09-paradigms/lim-ec-js-2017-1.md
Añade lecciones 05 y 06 (workshops)
Closes #45 
Closes #46
> 09 paradigms

- README.md
Para empezar, aun no está terminado pero dejo la idea de la propuesta tomando como referencia la propuesta de Lupo, la visión de los OKRs y lo que en otros bootcamps hacen, algunos _constraints_ a tener en cuenta y que necesito ayuda:
* Nombres de cursos aun no están definidos
* El wording del detalle de cada curso creo que no está del todo claro
* Los productos aun están por definirse
* Tiempo de cada curso
* Creo que el formato ahora no se entiende del todo
Especificaciones del `learning path`:
Primero, he tomado en cuenta los 4 perfiles que deseamos formar, es por ello que están las secciones `Common Core`, `JS Core`, `Front-End Development`, `Back-End Development`, `UX Design` y `UI Development`.
**Common Core:** aquí básicamente es ver lo que dijo Lupo en `Mi primera página web`, …
> Bootcamp syllabus

- 01-intro/01-introduction/00-welcome-and-orientation.md
- 01-intro/01-introduction/01-growth-mindset.md
- 01-intro/01-introduction/02-why-learn-to-code.md
- 01-intro/01-introduction/03-your-first-website.md
- 01-intro/01-introduction/04-prueba-tu-conocimiento.md
- 01-intro/02-variables-and-data-types/01-values-data-types-and-operators.md
- 01-intro/02-variables-and-data-types/02-variables.md
- 01-intro/02-variables-and-data-types/03-self-learning-MDN.md
- 01-intro/02-variables-and-data-types/04-comments.md
- 01-intro/02-variables-and-data-types/05-guided-exercises.md
- 01-intro/02-variables-and-data-types/06-prueba-tu-conocimiento.md
- 01-intro/README.md
Un poco de formato para facilitar el trabajo del parser que genera los cursos para nuestro LMS.
> 01 intro format

- 10-functional/higher-order-functions/README.md
Se agrega nueva lección sobre _higher-order functions_.
Como siempre cualquier comentario es más que bienvenido.
/cc @lupomontero
> Higher-order functions

- 08-deep-dive/README.md
En este PR se proponen las lecciones que se verán dentro del curso de JS Deep Dive y están basadas en el desarrollo del producto [`pinterestify`](https://github.com/Laboratoria/pinterestify).
@lupomontero para completar este curso me quedan dudas en 2 cosas: 
- El curso debería quedarse con el nombre de `JS Deep Dive` para educación continua? Actualmente, aparece con el nombre que le pusimos en la malla del Bootcamp `Really get to know JavaScript by building your own JavaScript library`. 
- Las lecciones de `performance` y `manejo de memoria` no estoy seguro si es bueno mantenerlo o diluirlo a través de todas las demás lecciones, opté por dejar las lecciones, y ver al momento del desarrollo del contenido si es necesario dejarlas o en todo caso tenerlas como _bonus_.
/cc @brecabal 
Cierra …
> Lecciones en base a producto (pinterestify) - JS Deep Dive

- 10-functional/02-immutability/README.md
> Correcciones en lección sobre inmutabilidad

- 10-functional/README.md
@lupomontero  Esto es una propuesta de ajuste en el contenido
> Ajuste en temario

- 08-deep-dive/01-intro/00-welcome.md
- 08-deep-dive/02-env/00-git+github.md
- 08-deep-dive/README.md
Se usará git y github durante el curso, así que se agrega como parte del entorno de trabajo, usaremos linters para lo cual deberemos instalar `Node.js` pero aun no está armado, igual se envía el PR para ir actualizándolo.
Cierra #129 
cc/ @brecabal
> JS Deep Dive: Entorno y metodología de trabajo

- 10-functional/async/README.md
Se agrega nueva lección sobre _asincronía_.
Cualquier comentario es más que bienvenido.
/cc @lupomontero
> Agrego lección sobre asincronía

- 10-functional/partial-application/README.md
> Agrego lección sobre aplicación parcial

- 10-functional/currying/README.md
> Mejoras en la narrativa de la lección de currying

- 02-interactive-site/01-basic-programming-in-javascript/09-quiz-1.md
Hola Chamo,
Te envío el PR del quiz1, solo está faltando la pregunta 20, que sería para el tema de command line.
Gracias
> add link Quiz 1: Programación básica en JavaScript

- 01-intro/03-control-flow/03-conditionals-and-loops.md
- 01-intro/03-control-flow/05-functions.md
- 01-intro/03-control-flow/08-guided-exercises.md
Hola,
Envío el PR con el feedback para control-flow.
Saludos
> feedback control-flow: Ruth Salvador

- 10-functional/01-pure-functions/README.md
- 10-functional/03-recursion/README.md
- 10-functional/README.md
- 10-functional/async/README.md
- 10-functional/partial-application/README.md
Y otros cambios menores...
/cc @lupomontero @onlyblank
> Agrego más referencias en artículos

- 01-intro/03-control-flow/03-conditionals-and-loops.md
> hotfix-169

- 01-intro/03-control-flow/03-conditionals-and-loops.md
This reverts commit c9211ebefdbf49fa983b9a9ae3e6bd8bb877a21e.
> Revert "fixes wrong return (#170)"

- 01-intro/03-control-flow/05-functions.md
Making sure latest change on 01-intro is reflected on gitbook.
> Updates text on medals example

- 02-basic-programming/01-basic-programming/13-code-challenges/arraytoObjectPart1/README.md
- 02-basic-programming/01-basic-programming/13-code-challenges/arraytoObjectPart1/boilerplate/arraytoObjectPart1.js
- 02-basic-programming/01-basic-programming/13-code-challenges/arraytoObjectPart1/solution/arraytoObjectPart1.js
- 02-basic-programming/01-basic-programming/13-code-challenges/arraytoObjectPart1/test/arraytoObjectPart1.spec.js
> Agregando ejercicio para el LMS test

- 02-basic-programming/01-basic-programming/14-solutions-code-challenges/README.md
- 02-basic-programming/02-final-products/01-final-products/README.md
Hemos visto la necesidad de incluir como parte de la experiencia de aprendizaje conocer sobre pseudocódigo, diagramas de flujo y poder exponer esta información en un archivo README.md que acompañe el código.
> chore(02-basic-programming): Añade lecciones sobre README.md, diagramas de flujo y pseudocódigo

- 03-interactive-site/02-html-and-css/05-box-model.md
- 03-interactive-site/02-html-and-css/05-boxmodel-and-display.md
Hola @chamodev 
Te envío el PR de la clase para box-model and display. Agradeceré tu feedback.
Gracias
> Añade clase de box-model and display

- 03-interactive-site/02-html-and-css/00-opening.md
- 03-interactive-site/02-html-and-css/02-html.md
- 03-interactive-site/02-html-and-css/03-css.md
- 03-interactive-site/02-html-and-css/05-boxmodel-and-display.md
- 03-interactive-site/02-html-and-css/06-positioning-and-floats.md
- 03-interactive-site/02-html-and-css/07-tipography-and-icons.md
- 03-interactive-site/02-html-and-css/09-quiz-1.md
- 03-interactive-site/02-html-and-css/11-guided-exercises.md
- 03-interactive-site/02-html-and-css/14-quiz-2.md
- 03-interactive-site/02-html-and-css/15-self-assessment.md
- 03-interactive-site/02-html-and-css/16-closing.md
- 03-interactive-site/README.md
Revisión de contenido:
* Agrega [juego de selectores](https://github.com/Laboratoria/css-diner) para lectura `03-css`.
* Arregla estándares de formato de "parte" de la unidad.
* Corrige algunos typos.
> chore(03-interactive): ajusta estándares y arregla typos

- 25-solutions-architecture/README.md
- README.md
@ivandevp porfa tu review para hacer el merge de este branch al master. Thks!
Son 2 cosas:
1. Actualiza el README.md del repo
2. Popone el README.md para un nuevo curso 25-solutions-architecture
cc: @lupomontero
> Updates README.md and adds new course (25-solutions-architecture)

- README.md
@ivandevp: aquí están los cambios que conversamos. Gracias por el feedback!!
> chore(README.md): fixes links and typos

- 03-interactive-site/00-html-and-css/05-tipography-and-icons/README.md
Agrega contenido de primera versión de `05-tipography-and-icons`.
cc/ @chamodev
> chore(03-interactive): lección de tipografía

- 03-interactive-site/00-html-and-css/10-code-challenges/README.md
Agrega enlaces a repositorios con instrucciones y boilerplate para desarrollar los retos de código de la unidad `00-html-and-css`.
> chore(03-interactive): retos de código `00-html-and-css`

- 03-interactive-site/00-html-and-css/02-css/README.md
- 03-interactive-site/00-html-and-css/08-seminar/README.md
- 03-interactive-site/00-html-and-css/09-guided-exercises/README.md
- 03-interactive-site/README.md
@chamodev corregí el tiempo de los ejercicios guiados. Revisando el flujo y analizando el comentario que me dijiste respecto a tener 2 seminarios. Considero lo siguiente:
* Tener 1 solo seminario, pero a la par de los ejercicios guiados. Es decir, repasar los conceptos de `HTML`, `CSS`, `displays` y hacer el ejercicio guiado de display, luego ver el siguiente tema y hacer los ejercicios una vez cerrado los conceptos. Espero darme a entender, no sabría muy bien donde lo podríamos poner.
> chore(03-interactive): tiempo de `00-html-and-css`

- 03-interactive-site/00-html-and-css/07-quiz/README.md
- 03-interactive-site/00-html-and-css/12-requiz/README.md
@shirley-suarez agregué algunas preguntas al quiz e hice algunas modificaciones en el formato de las preguntas que enviaste :)
@chamodev sería bueno tener tu feedback respecto a los quizzes.
Ps. Estoy subiendo el requiz en un siguiente commit.
> chore(03-interactive): quizzes de `00-html-and-css`

- 03-interactive-site/00-html-and-css/00-opening/README.md
- 03-interactive-site/00-html-and-css/01-html/README.md
- 03-interactive-site/00-html-and-css/03-boxmodel-and-display/README.md
- 03-interactive-site/00-html-and-css/04-positioning-and-floats/README.md
- 03-interactive-site/00-html-and-css/05-tipography-and-icons/README.md
- 03-interactive-site/00-html-and-css/07-quiz/README.md
- 03-interactive-site/00-html-and-css/09-guided-exercises/README.md
- 03-interactive-site/00-html-and-css/10-code-challenges/README.md
- 03-interactive-site/00-html-and-css/11-solutions-code-challenges/README.md
- 03-interactive-site/00-html-and-css/12-requiz/README.md
- 03-interactive-site/00-html-and-css/14-closing/README.md
> Corrige errores ortográficos y de redacción

- 01-intro/01-introduction/00-welcome-and-orientation.md
- 01-intro/01-introduction/01-growth-mindset.md
- 01-intro/01-introduction/02-why-learn-to-code.md
- 01-intro/01-introduction/03-your-first-website.md
- 01-intro/01-introduction/04-prueba-tu-conocimiento.md
- 01-intro/02-variables-and-data-types/01-values-data-types-and-operators.md
- 01-intro/02-variables-and-data-types/02-variables.md
- 01-intro/02-variables-and-data-types/03-self-learning-MDN.md
- 01-intro/02-variables-and-data-types/04-comments.md
- 01-intro/02-variables-and-data-types/05-guided-exercises.md
- 01-intro/02-variables-and-data-types/06-prueba-tu-conocimiento.md
- 01-intro/03-control-flow/01-recap.md
- 01-intro/03-control-flow/02-opening.md
- 01-intro/03-control-flow/03-conditionals-and-loops.md
- 01-intro/03-control-flow/04-practical-cases.md
- 01-intro/03-control-flow/05-functions.md
- 01-intro/03-control-flow/06-quiz-1.md
- 01-intro/03-control-flow/07-lecture.md
- 01-intro/03-control-flow/08-guided-exercises.md
- 01-intro/03-control-flow/09-code-challenges.md
- 01-intro/03-control-flow/10-solutions-code-challenges.md
- 01-intro/03-control-flow/11-quiz-2.md
- 01-intro/03-control-flow/12-self-assessment.md
- 01-intro/03-control-flow/13-closing.md
- 01-intro/README.md
Me he tomado la libertad de correr el linter en este curso y refactorizar el markdown para que pase todas las reglas establecidas en el linter.
> chore(01-intro): refactoriza estilo de markdown para adaptarse a linter

- 02-basic-programming/README.md
Quita estimaciones de duraciones de descripciones de unidades además de otros cambios menores para adaptar formato y estructura. Ahora las duraciones de curso y unidad se hacen programáticamente en LMS a partir de duración especificada en cada parte.
> 02-basic-programming: formato y estructuras

- 09-paradigms/03-proto/04-ejercicios/04-property-assignments/boilerplate/propertyAssignments.js
- 09-paradigms/03-proto/04-ejercicios/05-arrays-and-objects/README.md
- 09-paradigms/03-proto/04-ejercicios/05-arrays-and-objects/boilerplate/arraysAndObjects.js
- 09-paradigms/03-proto/04-ejercicios/05-arrays-and-objects/solution/arraysAndObjects.js
- 09-paradigms/03-proto/04-ejercicios/05-arrays-and-objects/test/arraysAndObjects.spec.js
> content(09-paradigms): migra el ejercicio 03-proto/04-ejercicios/05-arrays-and-objects

- 03-interactive-site/01-making-your-site-interactive/03-dom-manipulation/README.md
Se agrega descripción más detallada de estas funciones y su uso.
> Mayor detalle para funciones setInterval y setTimeout

- 03-interactive-site/01-making-your-site-interactive/09-guided-exercises/README.md
Propuesta de juego **tictactoe** en lugar de **el ahorcado**
> 03-interactive: propuesta tictactoe readme

- 01-intro/03-control-flow/01-recap.md
- 01-intro/03-control-flow/02-opening.md
- 01-intro/03-control-flow/03-conditionals-and-loops.md
- 01-intro/03-control-flow/04-practical-cases.md
- 01-intro/03-control-flow/05-functions.md
- 01-intro/03-control-flow/06-quiz-1.md
- 01-intro/03-control-flow/07-lecture.md
- 01-intro/03-control-flow/08-guided-exercises.md
- 01-intro/03-control-flow/09-code-challenges.md
- 01-intro/03-control-flow/10-solutions-code-challenges.md
- 01-intro/03-control-flow/11-quiz-2.md
- 01-intro/03-control-flow/12-self-assessment.md
- 01-intro/03-control-flow/13-closing.md
- 01-intro/README.md
Actualiza README y metadata para que sea consistente con el curso de `02-basic-programming`.
> chore(01-intro): actualiza README y metadata

- 01-intro/03-control-flow/01-recap.md
- 01-intro/03-control-flow/02-opening.md
- 01-intro/03-control-flow/03-conditionals-and-loops.md
- 01-intro/03-control-flow/04-practical-cases.md
- 01-intro/03-control-flow/05-functions.md
- 01-intro/03-control-flow/06-quiz-1.md
- 01-intro/03-control-flow/07-lecture.md
- 01-intro/03-control-flow/08-guided-exercises.md
- 01-intro/03-control-flow/09-code-challenges.md
- 01-intro/03-control-flow/10-solutions-code-challenges.md
- 01-intro/03-control-flow/11-quiz-2.md
- 01-intro/03-control-flow/12-self-assessment.md
- 01-intro/03-control-flow/13-closing.md
- 01-intro/README.md
* actualiza readme
* actualiza metadata
> chore(01-intro): actualiza README y metadata (#331)

- 09-paradigms/06-composition/00-opening/README.md
- 09-paradigms/06-composition/07-closing/README.md
Este PR añade y resuelve #321 
- Opening
- Closing
Para la unidad Nº6, esta es una primera versión de estos dos readme's
> 09-paradigms: primera versión para opening y closing de unidad 6

- 99-general-concepts/01-debugging/01-intro/README.md
@nicolethenerd I added a reading about `What is debugging?` and I basically remembered that once upon a time I wrote an article in medium, so I took that as a reference here:
https://medium.com/laboratoria-how-to/debugging-ac7295f52a5b
> chore(99-general-concepts): agrega lectura introductoria sobre debugging

- 26-angular-fundamentals/00-unidad/01-welcome.md
- 26-angular-fundamentals/01-unidad/01-prework.md
- 26-angular-fundamentals/01-unidad/02-quiz.md
- 26-angular-fundamentals/01-unidad/03-class.md
- 26-angular-fundamentals/02-unidad/01-prework.md
- 26-angular-fundamentals/02-unidad/02-quiz.md
- 26-angular-fundamentals/02-unidad/03-class.md
- 26-angular-fundamentals/03-unidad/01-prework.md
- 26-angular-fundamentals/03-unidad/02-quiz.md
- 26-angular-fundamentals/03-unidad/03-class.md
- 26-angular-fundamentals/04-unidad/01-prework.md
- 26-angular-fundamentals/04-unidad/02-quiz.md
- 26-angular-fundamentals/04-unidad/03-class.md
- 26-angular-fundamentals/README.md
Este pull request agrega la estructura basica del contenido, solo concentra en las primeras lecturas.
> 26 angular fundamentals

- 04-social-network/00-rwd/00-opening/README.md
- 04-social-network/00-rwd/01-grid-system/README.md
- 04-social-network/00-rwd/02-media-queries/README.md
- 04-social-network/00-rwd/03-rwd/README.md
- 04-social-network/00-rwd/04-quiz/README.md
- 04-social-network/00-rwd/06-guided-exercises/README.md
> 04-social-network: corrige errores de ortografía y redacción

- 04-social-network/01-css-frameworks/00-opening/README.md
- 04-social-network/01-css-frameworks/01-framework/README.md
- 04-social-network/01-css-frameworks/02-bootstrap/README.md
- 04-social-network/01-css-frameworks/03-materialize-and-more/README.md
- 04-social-network/01-css-frameworks/04-components/README.md
- 04-social-network/01-css-frameworks/05-quiz/README.md
- 04-social-network/01-css-frameworks/06-seminar/README.md
- 04-social-network/01-css-frameworks/10-requiz/README.md
@ivandevp done! métele el merge 💃
> corrige pequeños detalles ortográficos

- 04-social-network/03-design-process/00-opening/README.md
- 04-social-network/03-design-process/01-prototyping/README.md
- 04-social-network/03-design-process/02-seminar/README.md
- 04-social-network/03-design-process/03-closing/README.md
@ivandevp aquí agrego el contenido para las sesiones de UX del sprint 3. Es básicamente un día para hacer un prototipo en 90 minutos, que sumado a la reflexión y la organización son 2 horas. Y un día de `seminar` más el emisión del documental.
> 04 social network

- 04-social-network/02-jquery/10-requiz/README.md
Cambio de redacción en pregunta número 10, línea 107
Original
`10)  ¿Cuál es la opción que nos da un evento jQuery? `
Nueva
`10) ¿Cuál de las siguientes opciones corresponde a un evento de jQuery?`
> content(04-social-network): cambio de redacción en última pregunta 10-requiz de jQuery

- 04-social-network/00-rwd/00-opening/README.md
- 04-social-network/00-rwd/06-guided-exercises/README.md
- 04-social-network/00-rwd/09-requiz/README.md
@ivandevp Lo checas, por favor?
> content(04-social-network):  Agrega pendientes y correcciones del issue #415

- 14-chatbot/02-getting-started/01-design-principles/README.md
- 14-chatbot/02-getting-started/03-flujo-de-trabajo/README.md
- 14-chatbot/README.md
Actualización de contenido y nuevo contenido para la sesión 02
> 14 chatbot

- 05-deep-dive/03-foundations/00-opening/README.md
Se revisa y adapta la redacción de apertura para la unidad, tras unir ES6, funciones,estructuras de datos y fundamentos de JS en una sola unidad.
@AnaSalazar
> Este commit resuelve la tarea 1 del issue #481.

- 11-react/product-suggestion/instructor-handout.md
- 11-react/product-suggestion/student-handout.md
El pull request incluye el documento para las alumnas, y el documento para el instructor. Cualquier feedback será más que bienvenido.
Este producto fue uno de los entregables del Google.og Impact Sprint con Laboratoria.
> Definición de producto para el curso React 

- 13-angular/01-basics/03-product/README.md
- 13-angular/02-forms/02-product/README.md
- 13-angular/03-http-firebase/00-prework/README.md
- 13-angular/03-http-firebase/01-product/README.md
- 13-angular/04-routes/01-product/README.md
El proyecto final del curso de angular no se ajustaba a lo que se pasaba en cada unidad. A través de estos cambios se está intentando mejorar en claridad con respecto a lo que hay que hacer en el proyecto y se cambian los objetivos para que sean más afines a lo que cada unidad enseña.
> Nuevo proyecto para curso de ángular

- 11-react/01-intro/01-basics/README.md
- 11-react/01-intro/02-getting-started/README.md
- 11-react/01-intro/04-jsx/README.md
- 11-react/01-intro/05-jsx-practice/README.md
@lupomontero Agrego de nuevo el PR sin tanto drama :)
Saludos!
> cambios manu unidad 2

- 05-deep-dive/04-testing/01-basics/README.md
- 05-deep-dive/04-testing/02-frameworks/README.md
- 05-deep-dive/04-testing/04-browser/README.md
Hola @lupomontero! Mientras leía las lecturas que mandaste para el chapter de developers sobre testing, encontré algunos typos y los corregí para poder disfrutar el contenido aun mejor. 
Ps: No había leído el contenido pero me parece demasiado bueno 🎉, vi que la lectura de `05-headless` está incompleta, si puedes compartir la idea de que tenías pensado poner ahí sería muy bueno para poder aportar 😃 
cc/ @Laboratoria/developers
> chore(05-deep-dive): fixes some typos

- 02-basic-programming/00-welcome/00-opening/README.md
- 02-basic-programming/00-welcome/01-about-laboratoria/README.md
- 02-basic-programming/00-welcome/02-sprint-demo/README.md
- 02-basic-programming/00-welcome/03-learning-at-laboratoria/README.md
- 02-basic-programming/00-welcome/04-sprint-1-kickoff/README.md
- 02-basic-programming/01-shell+git/00-opening/README.md
- 02-basic-programming/01-shell+git/01-command-line/README.md
- 02-basic-programming/01-shell+git/02-git/README.md
- 02-basic-programming/01-shell+git/03-quiz/README.md
- SUMMARY.md
> Fix linter issues

- projects/01-cipher/README.md
cambie la palabra reto por proyecto como acordamos
> Cambio gramatical

- 01-intro/04-flow-control/00-opening/README.md
team SP traduzindo uma parte que faltava no LMS em português
> tradução Controle de Fluxos PT

- projects/02-data-dashboard/README.md
La idea es complementar la explicación del proyecto añadiendo la funcionalidad esperada o que ya tiene de cada carpeta y archivo. Es una forma de guía para que el código de las alumnas quede ordenado.
> Modificaciones a proyecto de data-dashboard

- package-lock.json
- projects/02-data-dashboard/README.md
Dado que se habían pisado los cambios, tomé un diff y vuelvo a subir los cambios propuestos para guiar a las estudiantes a través de los archivos que vienen en el proyecto inicialmente y cómo los deben ocupar.
> Reimplementación de explicación de archivos para data dashboard

- topics/browser/04-xhr/03-working-with-apis/01-third-party-apis/README.md
Estoy revisando material que hay de  APIs  ....hasta el momento solo he hecho cambios menores.
en el README.md de los pros y contra del uso de APIs  agregue Que es LOPD que solo se menciona la sigla.
sigo revisando ...el resto del material
> Cambios menores  Pros y contras del uso de APIs

- projects/03-social-network/README.md
@lupomontero  este es el nuevo PR :)
> edición redacción y habilidades blandas

- 03-interactive-site/02-ux-design/01-el-equipo-de-desarrollo/README.md
- 03-interactive-site/02-ux-design/03-ux-design-vs-ui-design/README.md
- 03-interactive-site/02-ux-design/04-navegacion/README.md
- 03-interactive-site/02-ux-design/07-seminar/README.md
- 03-interactive-site/02-ux-design/09-ux-challenges/README.md
This PR fixes some videos there were not showing, changes some links to Portuguese and fix wrong links
> Fix videos and links in ux unit

- projects/03-social-network/README.md
This is already mentioned in the main objectives
> fix(projects/03-social-network): removes hacker editin requirement about routing

- projects/03-social-network/README.md
También agrego una mini sección sobre historias de usuario en la parte de implementación y el contenido de referencia.
> ajustes de wording y estructura 

- .mdlintignore
- projects/04-md-links/.editorconfig
- projects/04-md-links/.eslintrc
- projects/04-md-links/.gitignore
- projects/04-md-links/README.md
- projects/04-md-links/index.js
- projects/04-md-links/package.json
- projects/04-md-links/test/md-links.spec.js
Todavía falta completar `README.md` e implementar tests...
> content(projects/04-md-links): refactoring project for v2.x

- projects/04-md-links/README.md
> content(projects/04-md-links): agrega rúbrica de evaluación

- projects/04-md-links/README.md
@lupomontero , envío el PR con el readme para este proyecto. De manera base se está incluyendo los puntos de checklist por favor, de ser necesario incluir los pertinentes  y  los cambios necesarios.
> content(projects/04-md-links): Incluye el contenido de los PR.

- projects/06.1-silicon-valley-FE/README.md
@diegovelezg Acá está el esqueleto de SV para FE. Después de esto, le vamos a agregar los links externos.
> Update SV README.md

- projects/04-md-links/README.md
See https://github.com/Laboratoria/curricula-js/pull/685#pullrequestreview-145855656
> content(projects/04-md-links): adds tip about making your NPM modules installable via GitHub

- projects/04-social-network-frameworks/README.md
Corrección de niveles en habilidades blandas
> V2.x Niveles habilidades blandas

- projects/04-social-network-frameworks/README.md
Pequeños cambios en redacción sobre frameworks y librerías.
> V2.x - Arreglando redacción sobre frameworks y librerias Social Network Framework

- projects/04-social-network-frameworks/README.md
Faltan videos de React @lizzie136 y de Vue @espinozasenior
> agrega videos (intro y Angular) y guía de planificación

- projects/04-social-network-frameworks/README.md
@lupomontero he agregado la opción de despliegue y la configuración de entornos (prod y dev) con el uso de la herramienta webpack. 
¿Entraría al scope del proyecto?
> Opción despliegue - checklist de proyecto

- projects/05-bq-node/README.md
- projects/05-bq-node/index.js
- projects/05-bq-node/routes/auth.js
- projects/05-bq-node/routes/users.js
- topics/angular/01-basics/01-cli/README.md
La idea es dejar algunos comentarios guía dentro de la aplicación. Además agrego un párrafo para que quienes no tienen curl, puedan probar la API a través de postman.
> Agrega comentarios y algunos detalles a proyecto bq-node

- projects/01-cipher/README.md
cc/ @Laboratoria/bootcamp-coaches
> projects(cipher): adds checklist

- projects/02-data-lovers/EXTRA.md
> project(data-lovers): agrega info de requerimientos 'extra' para la segunda parte del proyecto

- projects/01-cipher/README.md
- projects/01-cipher/src/index.html
- projects/01-cipher/test/cipher.spec.js
Tarea relacionada al issue #761
> project(cipher): Actualizaciones con cambios aplicados en Lima

- projects/02-data-lovers/src/data/lol/lol.json
arreglando errores en la data, algunas url de los splash no estaban funcionando
> arreglando errores en la data, algunas url de los splash no estaban funcionando

- projects/03-social-network/README.md
Hola estas son las modificaciones que hemos realizado en el proyecto:
- No utilizamos local storage solo Firebase: esto es porque en el bootcamp pasado todas las estudiantes lograron implementar el uso de firebase tanto para la autentificación y el muro. Me gustaría saber como fue en las otras sedes @Laboratoria/bootcamp-coaches ?....
- No librerías ni frameworks solo vanilla js y css: el cambio de no poder utilizar un framework de css (Bootstrap/ Materialize, etc...) es porque queremos que las estudiantes refuerzan y mejoren el uso de CSS.
- La aplicación que realicen deberá de ser una SPA (pensamos que seria bueno dar una píldora para cubrir este tema)
- UX: se quita el requerimiento de Benchmark ya que es un tópico que no vieron durante common core y dejar todos los requerimientos que …
> Modificando Readme de proyecto social network

- projects/04-job-application/README.md
@diegovelezg y @lupomontero aquí va el PR de modificación de el proyecto según lo conversado.
> Update Silicon Valley a Job Application

- projects/04-job-application/README.md
@diegovelezg cambio de redacción de características y suma link a check list.
> Update Job Application.md

- projects/01-cipher/test/cipher.spec.js
Tal cual indicado en el issue #792 envío la corrección del código.
> Fix duplicated test

- projects/02-data-lovers/README.md
Hi @lupomontero, I just found a blog post with an equivalent data references of the original one posted on IBM.
ISSUE-33
> (2-data-lovers) replace broken link

- topics/javascript/05-objects/06-practice/01-object-properties-counter/README.pt-BR.md
> i18n(topics): Adds portuguese translation

- README.md
> fix(readme): Replaces projects map image with text version

- topics/javascript/01-basics/01-values-variables-and-types/README.md
- topics/javascript/01-basics/01-values-variables-and-types/README.pt-BR.md
- topics/javascript/01-basics/05-quiz/README.md
- topics/javascript/01-basics/05-quiz/README.pt-BR.md
For reference, the following structure and conventions have been agreed wrt quizzes:
1. Quizzes are made up of _questions_
2. Each _question_ contains the following elements:
- _title_: this has to be text only (NO MARKUP HERE)
- _description_: this is the bit between the title and _options_ (see below). It is optional and can include arbitrary markup.
- _options_: This is a list of possible answers. We can include markup here, and should include it when necessary to understand the suggested answers. For example, code should be wrapped in `<code>` tags (ie: <code>\`123\`</code> or <code>\`const a = 'a string'\`</code>)
cc/ @raulingg @MaiaRojas @rafaelbcerri @paclaraujo @JulianaAmoasei
> topic(javascript): Refactors first quiz making use of markup in question description and options

- topics/javascript/01-basics/04-guided-exercises/README.md
- topics/javascript/01-basics/04-guided-exercises/README.pt-BR.md
This is needed becaue the videos still use old stuff like `var`...
In the near future we will be replacing this videos ;-)
> topic(javascript): Adds note before old videos

- topics/javascript/01-basics/02-variables/README.pt-BR.md
This PR is related to Issue #906
> Translate note fix

- projects/01-cipher/README.pt-BR.md
This PR is related to issue #912
> translate(cipher): update pt-BR learning objectives

- projects/02-data-lovers/src/data/rickandmorty/rickandmorty.js
- projects/02-data-lovers/src/data/rickandmorty/rickandmorty.json
*The image paths were changed by the image paths in the rick-and-morty-images repository.
> project(data-lovers):  Update the RickandMorty dataset

- projects/01-card-validation/.babelrc
- projects/01-card-validation/README.md
- projects/01-card-validation/test/validator.spec.js
- Agrega test adicional para método isValid.
- Configuración de babel: `babelrc`
- Arregla objetivos de aprendizaje.
> project(card-validation): Agrega test adicional para método isValid y babelrc 

- projects/04-burger-queen-api-client/README.md
Hola @lupomontero :hand:  como te compartí el otro día en Lima ahora que tenemos en el equipo de bootcamp @fakel decidimos definir los objetivos de aprendizaje para `vue.js` guiándonos de los que teníamos para `react` y `angular` en este proyecto.
Aquí la lista de los objetivos que definimos:
- [Instancia de Vue.js](https://es.vuejs.org/v2/guide/instance.html)
- [Datos y métodos](https://es.vuejs.org/v2/guide/instance.html#Datos-y-Metodos)
- [Uso y creación de Componentes](https://vuejs.org/v2/guide/components.html)
- [Props](https://es.vuejs.org/v2/guide/components.html#Pasando-datos-a-componentes-secundarios-con-Props)
- Directivas ([v-bind](https://es.vuejs.org/v2/api/#v-bind) | [v-model](https://es.vuejs.org/v2/guide/forms.html))
- Renderizado condicional …
> project(burger-queen-api-client): agregando objetivos de aprendizaje de Vue.js

- projects/01-card-validation/README.md
- projects/01-cipher/README.md
closes #949 
La idea es actualizar el README los proyectos Cipher y Card-validation para que puedan ser usados de manera remota y en parejas.
Estos cambios deben de incluir
> Cipher & Card-validation to remote learning

- .mdlintignore
- README.pt-BR.md
closes #946 
Continuando con el trabajo de #946, envío el PR para tener la traducción del README incluyendo la lista de colaboradores.
Necesitamos agregar el archivo a `.mdlintignore` para poder tener la lista de colaboradores.
---
feat(main): Add pt-BR bootcamp readme
Co-authored-by: Juliana Amoasei <juliana.amoasei@gmail.com>
Co-authored-by: Paloma Araújo <paloma@laboratoria.la>
> Add pt-BR bootcamp readme

- projects/02-movie-challenge/README.md
feat(proj): Add Movie challenge project
Agregamos el proyecto Movie challenge que ya estaba siendo usado en algunas sedes como reto mid-bootcamp.
Este proyecto no tiene _boilerplate_ puesto que las estudiantes tienen la libertad de proponer su propia solución.
> Proyecto Movie-challenge

- projects/02-data-lovers/README.pt-BR.md
- projects/02-data-lovers/src/data/lol/README.pt-BR.md
- projects/02-data-lovers/src/data/lol/lol.js
- projects/02-data-lovers/src/data/lol/lol.json
- projects/02-data-lovers/src/data/pokemon/README.pt-BR.md
- projects/02-data-lovers/src/data/rickandmorty/README.pt-BR.md
closes #962 
This is a mirror PR with #962 with 2 commits.
> Data lovers update

- projects/01-cipher/README.md
- projects/02-data-lovers/README.md
- projects/03-social-network/README.md
Ahora que se han listado los objetivos de aprendizaje de los proyectos
para los formularios de feedback, pasamos a actualizar los READMEs para
mantener consistencia.
Referencia de listado de OAs: https://docs.google.com/spreadsheets/d/1iiAm-CKatIv32RgX_CAN-vOYr6hDKh5flyHfPY3q6pA/edit#gid=860874863
Agrego actualizaciones de OAs para estos 3 primeros proyectos para ir agilizando el merge.
> Actualiza OAs de Cipher, Data-lovers y Social-network siguiendo formulario de feedback

- projects/04-burger-queen-api-client/README.md
- projects/04-burger-queen-api/README.md
- projects/04-burger-queen/README.md
- projects/04-md-links/README.md
Actualiza OAs del resto de proyectos restantes del Core del Bootcamp JS:
- Md-links
- Burger-queen
- Burger-queen-api
- Burger-queen-api-client
Referencia: https://docs.google.com/spreadsheets/d/1iMipHxaYhJxTvDysCcfE42P_Wa-sowFqMM2XJbbcEBM/edit#gid=860874863
> Actualiza OAs del resto de proyectos Core

- projects/01-card-validation/README.md
- projects/01-cipher/README.md
Ya que se pudo grabar el video, me parece importante poder compartirlo con
las estudiantes que recién están empezando. Por eso es que se agrega a los 2
primeros proyectos recomendados de la curricula, pero con la pregunta de si
debería estar solo acá.
> Agrega video sobre resolución de problemas con JavaScript

- projects/01-card-validation/README.md
Fuente: https://docs.google.com/spreadsheets/d/1iMipHxaYhJxTvDysCcfE42P_Wa-sowFqMM2XJbbcEBM/edit?ts=5edfae7b#gid=860874863
> Actualiza OAs de Card-validation siguiendo formulario de feedback

- projects/03-small-businesses/README.md
Plataforma de ventas en línea -> Emprendimientos
> Actualizar nombre de proyecto UX a Emprendimientos

- projects/01-card-validation/README.md
- projects/04-md-links/README.pt-BR.md
UPDATE dos Objetivos de Aprendizagens no readme pt-BR
se puderem dar uma olhada... @paclaraujo @vdemario @gabrieluizramos
> [translation] update OA do README

- projects/01-card-validation/FAQ.md
- projects/01-cipher/FAQ.md
Basado en la contribución de https://github.com/Laboratoria/bootcamp-ejecucion/issues/77#issuecomment-644776026
Aunque por ahora el contenido es el mismo, se crean 2 archivos porque en el
tiempo pueden ir apareciendo preguntas específicas a cada proyecto.
> Agrega Preguntas frecuentes a los proyectos de Cipher y Validación de tarjeta

- projects/02-data-lovers/FAQ.md
Basada en la contribución de https://github.com/Laboratoria/bootcamp-ejecucion/issues/77#issuecomment-644776026
> Agrega Preguntas frecuentes a Data-lovers

- projects/02-emergency-room/README.md
- projects/02-movie-challenge/README.md
- projects/03-visitors/README.md
- projects/04-news-alerts/README.md
Nos faltaba diferenciar los proyectos.
Explicación sobre qué es un proyecto de extensión:
https://github.com/Laboratoria/bootcamp/wiki/Anatom%C3%ADa-de-un-proyecto-de-extensi%C3%B3n
> Agrega indicación que son proyectos de extensión

- projects/00-trivia/README.md
Nos faltaba estandarizar este proyecto.
Fuente: https://docs.google.com/spreadsheets/d/1iMipHxaYhJxTvDysCcfE42P_Wa-sowFqMM2XJbbcEBM/edit#gid=860874863
> Actualiza OAs de Trivia siguiendo formulario de feedback

- .mdlintignore
- projects/learning-objectives.md
Esto nos servirá para referenciar los proyectos de extensión.
El archivo markdown es el resultado de un script por lo que prevenimos
conflictos agregándolo al `.mdlintignore`.
> Agrega listado completo de Objetivos de Aprendizaje

- projects/02-emergency-room/README.md
- projects/02-movie-challenge/README.md
- projects/03-visitors/README.md
- projects/04-news-alerts/README.md
- projects/06-open-project/README.md
En este caso, como los proyectos son creados a partir de estas carpetas, no podemos
usar referencias dinámicas ya que devolverían un 404.
> Modifica a urls estáticas

- projects/04-burger-queen-api/index.js
- projects/04-burger-queen-api/package-lock.json
- projects/04-burger-queen-api/package.json
El PR incluye también un fix de un typo :see_no_evil: 
Closes #953 #989
> Actualiza dependencias del proyecto burger-queen-api

- projects/02-data-lovers/README.pt-BR.md
- projects/02-data-lovers/src/data/ghibli/README.pt-BR.md
> fix translation issues #1044

- projects/04-md-links/README.md
La idea de este cambio es agregar una cuantas recomendaciones iniciales para quien por primera vez enfrenta un proyecto casi exclusivamente de JS y con mucho uso del Terminal.
Previamente el comentar que algo equivalente a los prototipos de baja o alta podría ser un diagrama o pseudo código quedaba de parte de coaches y, dado que la mayoría de estudiantes probablemente nunca han escuchado o trabajado con esas herramientas orientadas al código, podría ser una buena idea comentarlo en la sección de achicando u otra.
Entre otros puntos, se mencionan explícitamente las recursividad, las promesas y los callbacks para darles algo de relevancia más allá de los objetivos de aprendizaje.
Las propuestas concretas de Achicando el problema incluyen los siguientes títulos inicialmente:
1. Empieza con …
> MDLinks: Más pistas, énfasis y recomendaciones para achicar el problema

- projects/04-md-links/README.md
En este proyecto todas las consultas HTTP son GET (o HEAD) y el foco principal (desde el punto de vista de HTTP) son los códigos de status, que son los que nos permiten saber si un link está _roto_.
cc/ @raulingg @merunga
> project(md-links): Replaces HTTP Verbs with Status Codes in learning objectives

- topics/browser/02-dom/04-events/README.md
- topics/css/01-css/02-boxmodel-and-display/README.md
> fix(topics): Fixes missing images in css/01-css/02-boxmodel-and-display y browser/02-dom/04-events

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/05-roman-numerals-slack/README.md
- projects/05-roman-numerals-slack/project.yml
- projects/05-roman-numerals/.gitignore
- projects/05-roman-numerals/README.md
- projects/05-roman-numerals/index.spec.js
- projects/05-roman-numerals/package.json
- projects/05-roman-numerals/project.yml
> Agrega proyectos roman-numerals y roman-numerals-slack

- projects/02-memory-match/README.pt-BR.md
> add readme pt-BR memory match

- projects/02-data-lovers/src/data/ghibli/ghibli.js
- projects/02-data-lovers/src/data/ghibli/ghibli.json
Hola team! Estoy actualizando las imágenes del data set ghibli, esto gracias al [PR](https://github.com/Laboratoria/LIM015-data-lovers/pull/15) que envío una estudiante al repositorio LIM015-data-lovers. Gracias @santiaguf por mantenerme al tanto. 🚀 🙌 
@Laboratoria/coaches @lupomontero 🌟
> project(data-lovers): update images of data set (ghibli) at data lovers project

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- projects/05-wordpress-plugin/.gitignore
- projects/05-wordpress-plugin/README.md
- projects/05-wordpress-plugin/apache2/ports.conf
- projects/05-wordpress-plugin/apache2/sites-available/000-default.conf
- projects/05-wordpress-plugin/apache2/sites-available/001-php-playground.conf
- projects/05-wordpress-plugin/apache2/sites-enabled/000-default.conf
- projects/05-wordpress-plugin/apache2/sites-enabled/001-php-playground.conf
- projects/05-wordpress-plugin/docker-compose.yml
- projects/05-wordpress-plugin/php-playground/hola.php
- projects/05-wordpress-plugin/php-playground/index.html
- projects/05-wordpress-plugin/project.yml
> Agrega proyecto wordpress-plugin

- projects/04-burger-queen-api-client/README.pt-BR.md
adding bq-api-client translation #1051
>  proyect(bq-api-client): add README pt-BR translation

- projects/04-burger-queen/README.md
@danielislas3 y yo hemos agregado informacion de netlify y netlify cli.
Para este issue https://github.com/Laboratoria/bootcamp/issues/1023
(no puedo linkearlo a la derecha no se porque)
> Agregando info de netlify en Burger Queen

- projects/04-burger-queen/README.md
@lupomontero @mfdebian 
I found an error in the wording
> Solving error in the wording, project 04-burger-queen

- learning-objectives/intl/pt.yml
- fixed links and some words
- added translated OA:
issue #1140 
close incorrect PR #1138
> Translation(add news oa)

- projects/04-md-links/README.md
> fix(content): Fixes a typo and ads --stats as options. 

- projects/04-md-links/project.yml
> fix(content): OA de gh-pages no correspondia a este proyecto

- projects/04-burger-queen/README.md
> chore(fix): Fix typo in burguer-queen ES README.md

- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
fixes #1200 
@moniyama Eu posso pedir para você se você puder fazer uma revisão superficial disso caso haja um erro de ortografia? :pray:
> chore(OA-translation): Normalize OA's titles between ES and PT translations

- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
Fixes #1210 
Typo `@Ouput` -> `@Output` in the title of OA
> bug(fix): correct output in es and pt yml

- .mdlintignore
- projects/06-job-application/Activities.md
- projects/06-job-application/Activities.pt-BR.md
- projects/06-job-application/Mentoring.pt-BR.md
- projects/06-job-application/README.pt-BR.md
> Ja translation pt

- projects/01-card-validation/README.md
- projects/01-card-validation/README.pt-BR.md
- projects/01-cipher/README.md
> replace cmder.net with .app in cipher and card Fixes #1235

- projects/04-md-links/README.md
> remove stats as option to mdlinks

- projects/01-card-validation/.eslintrc
- projects/01-cipher/.eslintrc
- projects/02-data-lovers/.eslintrc
- projects/02-emergency-room/.eslintrc
> chore(eslint): adds 4 new rules to webdev projects/ of levels 1 and 2

- learning-objectives/intl/pt.yml
fixing a small translation error in this OA
> 🐞 fix: OA js/testing/compatibility translation PT-BR

- projects/06-job-application/Activities.pt-BR.md
- projects/06-job-application/README.pt-BR.md
During SAP008 some changed were applied on this cohort repo:
1. fix small translations missing in JA
2. update pt-br videos for JA
> Fix/JA pt-BR version

- projects/02-data-lovers/src/data/harrypotter/README.md
- projects/02-data-lovers/src/data/harrypotter/README.pt-BR.md
> chore(data-lovers): Adds a disclaimer for the Harry Potter data

- projects/01-card-validation/README.md
- projects/01-card-validation/README.pt-BR.md
- projects/01-cipher/README.md
- projects/01-cipher/README.pt-BR.md
- projects/02-data-lovers/README.md
- projects/02-data-lovers/README.pt-BR.md
- projects/02-memory-match/README.md
- projects/02-memory-match/README.pt-BR.md
- projects/03-social-network/README.md
- projects/03-social-network/README.pt-BR.md
- projects/04-burger-queen-api-client/README.md
- projects/04-burger-queen-api-client/README.pt-BR.md
- projects/04-burger-queen/README.md
- projects/04-burger-queen/README.pt-BR.md
- projects/04-md-links/README.md
- projects/04-md-links/README.pt-BR.md
- projects/04-notes/README.md
Adds estimated time of completion (in sprints) for Web Dev projects.
closes #1277
closes #1282
> chore(projects): Adds estimated time of completion

- public/index.html
- public/manifest.json
Este cambio hace que la UI de curriculum siga la misma convención que las otras interfaces del nuevo ecosistema de Laboratoria.
Sería bueno que una vez integrado esto se haga un nuevo despliegue (podemos hacer un release de tipo `patch` para no esperar el siguiente `minor`).
> feat(public): Actualiza título en HTML y manifest.json

- projects/01-cipher/README.md
- projects/01-cipher/README.pt.md
with Brazilian Portuguese subtitles to project's README
closes #1301
> feat(translation): Adds Carlos Mendoza's Getting Started video 

- src/components/Track/Topics.jsx
> fix(Topics): Fixes invalid components nesting in Topics React component

- DEPLOYMENT.md
Despues haciendo el deploy, agregue dos puntos mas para recordarme cuando publica el publicacion de release.
> Update DEPLOYMENT.md with small changes about publication

- projects/06-job-application/Activities.md
closes https://github.com/Laboratoria/job-application/issues/9
> fix(docs): Se actualiza link de guia para tu CV en la industria

- projects/00-trivia/README.md
- projects/00-trivia/README.pt.md
Estor colocando dos opciones en vez de replit, si elegimos una de ellas, haría un tutorial para reemplazar el de replit,  o dos tutoriales, si se elige los dos.
Fixes #1387
> cambio de replit a codepen y glitch

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/04-burger-queen-api-client/README.md
- projects/04-burger-queen-api-client/project.yml
fixes #1361
incluye todo lo de #1398
> BQ-API-Client con react y typescript

- projects/04-burger-queen-api-client/README.pt.md
- projects/04-burger-queen-api/README.md
Hacer los mismos cambios  que ya se habian sumado en español, borrado de mockoon y nock.
> Cambio nock mockoon pt

- projects/04-burger-queen-api-client/README.md
- projects/04-burger-queen-api-client/README.pt.md
> Mejora en la redaccion de las opciones para consumir API

- projects/01-text-analyzer/README.md
> fix: agrega Resumen de Proyecto a Text Analyzer

- projects/05-movie-challenge-fw/project.yml
> fix: oas parecido a bq api client fixes #1483

- projects/01-text-analyzer/read-only/test/oa/oa-html.spec.js
Fixes #1518 
https://github.com/Laboratoria/bootcamp/issues/1518#issuecomment-1673263945
> (oa-html):Delete unit test ul has class atrribute

- projects/02-data-lovers/.gitignore
- projects/02-data-lovers/README.md
- projects/02-data-lovers/package.json
- projects/02-data-lovers/test/data.js
- projects/02-data-lovers/test/dataFunctions.spec.js
- projects/02-data-lovers/tests-read-only/.eslintrc
- projects/02-data-lovers/tests-read-only/e2e/app.spec.js
- projects/02-data-lovers/tests-read-only/oa/oa-css.spec.js
- projects/02-data-lovers/tests-read-only/oa/oa-html.spec.js
- projects/02-data-lovers/tests-read-only/oa/oa-web-api.spec.js
https://github.com/Laboratoria/impl-dev-data-lovers/milestone/1
> Feat/data lovers makeover cambios de feedback - oas, e2e, README

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/02-data-lovers/project.yml
> Prompting learning objectives 1510

- projects/02-dataverse-explorers/README.md
- projects/02-dataverse-explorers/src/dataFunctions.js
- projects/02-dataverse-explorers/src/main.js
- projects/02-dataverse-explorers/src/view.js
> cambios con feedback DEV011 - resaltar root, modificar instruccion de view

- projects/02-dataverse/package.json
Linea 10 de package.json, script test con bug para windows
Pull Request de Adrian (no pudo enviar por permisos)
> fix:script test in package.json fail in windows

- projects/04-burger-queen-api-client/README.md
- projects/04-burger-queen-api-client/README.pt.md
Este PR es parte de #1544 
- Se mueve la Historia de Usuaria 5 y 6 (CRUD de productos y usuarios) a Hacker Edition. 
- Este PR va a acompañado con otro [PR del API Mock]((https://github.com/Laboratoria/burger-queen-api-mock/pull/3)) donde se incluyen nuevos productos y usuarias
> Hacker Edition para BQAC

- projects/03-dataverse-chat/.babelrc
- projects/03-dataverse-chat/.editorconfig
- projects/03-dataverse-chat/.eslintrc
- projects/03-dataverse-chat/.gitignore
- projects/03-dataverse-chat/package.json
- projects/03-dataverse-chat/src/app.js
- projects/03-dataverse-chat/src/index.html
- projects/03-dataverse-chat/src/index.js
- projects/03-dataverse-chat/src/views/Example.js
> Add first version of the boilerplate

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/03-dataverse-chat/project.yml
Closes #1609 
Aqui puedes ver como se ve en el parte de Objetivos
https://github.com/Laboratoria/CURR-dataverse-chat#7-objetivos-de-aprendizaje
> Dataverse chat objectives 1609

- projects/02-dataverse/README.md
- projects/02-dataverse/README.pt.md
> Dataverse README portugues

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
Addresses #1626 
Me gusta primero validar la estructura/hierarquia de OAs y sus nombres.
Despues voy agregando links y recursos con titulos en espanol y portugues.
> Java Objetivos de Aprendizaje

- projects/02-dataverse/README.md
- projects/02-dataverse/package.json
- projects/02-dataverse/src/index.html
Algunas errores de redacion y titulos que encontro @reloadercf haciendo la implementacion.
> fix: 📝 Titles of project and edit sintax (Dataverse)

- learning-objectives/intl/es.yml
> fix: Java oa string typo

- package-lock.json
- package.json
Updating outdated dependencies for 7.7
> Dependencies release 7.7

- projects/01-design-detectives/project.yml
Addresses #1715 
Depends on #1710
> Design detectives OAs 1715

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
This PR #1728 add the OAS of django with rest framework
> docs: :bricks: Add django rest-framework oas

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/05-guess-the-number/README.md
- projects/05-guess-the-number/README.pt.md
- projects/05-guess-the-number/docs/README-java.md
- projects/05-guess-the-number/docs/README-java.pt.md
- projects/05-guess-the-number/docs/README-python.md
- projects/05-guess-the-number/docs/README-python.pt.md
- projects/05-guess-the-number/project.yml
Addresses #1687 
Objectives for oth Guess the Number and Fleet Management projects
Basic pure python concepts, Flask and Django
> Python learning objectives

- projects/02-dataverse/README.pt.md
Corrigido o nome das `data-testid` necessárias para rodar os testes e2e
> 🐞 fix: readme dataverse data-testid translation

- projects/05-fleet-management-api/README.md
- projects/05-fleet-management-api/docs/README-python.md
> Adds python stack to project

- projects/03-dataverse-chat/README.pt.md
- projects/03-dataverse-chat/docs/01-milestone.pt.md
- projects/03-dataverse-chat/docs/02-milestone.pt.md
- projects/03-dataverse-chat/docs/03-milestone.pt.md
- projects/03-dataverse-chat/docs/04-milestone.pt.md
- projects/03-dataverse-chat/docs/05-milestone.pt.md
Updates:
- README: change slack channel to pt & add hitos topic
- add files `0x-milestones.pt.md` in /docs directory with translations 
CC @myakiju
#1723
> Adding translation hitos in dataverse chat

- projects/03-dataverse-chat/docs/01-milestone.md
- projects/03-dataverse-chat/docs/03-milestone.md
> fix: links to guide router-spa and more explicit link text

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
Adding "Components Lifecycle" as Learning Objective of Angular
> Adding angular learn objective

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
Indentation error on build, also making singular to match title better
> fix: component-lifecycle oa indentation and singular

- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- projects/02-design-assigned/project.yml
- projects/02-mindset-mvp/project.yml
- projects/02-uxploradoras-ui/project.yml
- projects/03-uxploradoras-ux/project.yml
> feat: adds updates to titles descriptions and new OA

- projects/03-movie-challenge/project.yml
Addresses #1818 
Puedes verficiar [con ejemplo de readme y objetivos](https://github.com/Laboratoria/TEST-movie-challenge) tambien
> Adds objectives to movie challenge

- projects/02-dataverse/tests-read-only/oa/oa-web-api.spec.js
> Added Conditional to fix/add-validation-event-param-test-oas-web-api

- .mdlintrc
- learning-objectives/data.yml
- learning-objectives/intl/es.yml
- learning-objectives/intl/pt.yml
- projects/05-artist-launch/README.md
- projects/05-artist-launch/README.pt.md
- projects/05-artist-launch/project.yml
- projects/05-sql-student-database/README.md
- projects/05-sql-student-database/README.pt.md
- projects/05-sql-student-database/project.yml
Add Artist Launch and SQL Student Database Project
> Add Artist Launch and SQL Student Database Project.

- projects/03-dataverse-chat/README.md
> fix: link to slack README.md

- projects/02-dataverse/tests-read-only/oa/oa-prompting.spec.js
> fix: shortDescription in  oa-prompting.spec.js
